Gliederunspunkte ausbauen
Rusi91/basisdokument pull request #30
Opened 2022-08-24 18:34 UTC by MaximilianHuber

Gliederungspunkte haben jetzt beiträge und werden flexibel aus den Json dummydaten gebaut

2022-08-24 19:07 UTC, silvia-ivanova-github-rep requested changes
Ich habe den Code getestet und die Gliederungspunkte werden gezeigt.

2022-08-24 19:07 UTC, silvia-ivanova-github-rep commented on basisdokument-application/src/backend.json
> +}
Laut Github wäre es gut, wenn man am Ende der Datei eine neue Zeile hinzufügt.

2022-08-24 19:07 UTC, silvia-ivanova-github-rep commented on basisdokument-application/src/components/LinearPosts/LinearPosts.module.css
> +}
Hier auch sollte man neue Zeile hinzufügen. :)

2022-08-24 22:47 UTC, MaximilianHuber commented on basisdokument-application/src/backend.json
> +}
Ist erledigt

2022-08-25 10:19 UTC, silvia-ivanova-github-rep approved these changes

2022-08-25 12:24 UTC, merged